### PR TITLE
fix: Implement a working version of React Flagpack

### PR DESCRIPTION
**Pull request by zoeyfrisart**
This version implements a CLI that will auto-inject the flags into the static folder of a given project.
_(Could be improved in the future to auto-detect the framework/static folder of a project)_

This rework works by removing the dynamic required implementation that was not only causing issues but was also not tree-shaking correctly when looking at the resulting bundle.

This new implementation should work properly in:
- NextJS (App and page router)
- Create-react-app
- Gatsby
- Remix

Other frameworks have yet to be tested.

Also, I took the time to refactor the build process to vote instead of the roll-up.
Also exports the props interface to make the component easier to use with TypeScript

CLOSES: #69 #70 #58 #55 #47 #40
Possibly fixes: #45 & #46 but that needs more testing

---
This change is a breaking change that would also require changes to the flatpack website documentation (and requires changes on the user's part). I have marked this as a breaking change, which means the version will increase to 2.0.0

### CODE REVIEW

**Comment by zoeyfrisart** [comment]
@CodiumAI-Agent /review

**Comment by zoeyfrisart** [comment]
@CodiumAI-Agent /review

**Comment by tnmdynamiq** [comment]
Is this going to be merged at some point in the near future?🤞 @zoeyfrisart

**Comment by zoeyfrisart** [comment]
@tnmdynamiq I certainly hope so, but it needs a review from the rest of our dev team.
I'll see if I can push for some time in the upcoming week(s) to review this pull request.

**Comment by tnmdynamiq** [comment]
> @tnmdynamiq I certainly hope so, but it needs a review from the rest of our dev team. I'll see if I can push for some time in the upcoming week(s) to review this pull request.

Thank you very much for clarifying! Much appreciated, I will keep my eye out for it.

**Comment by arush** [comment]
would love for this to be merged soon

**Comment by depsimon** [comment]
@zoeyfrisart Would it be possible to release this as a @next version on npm or something like that?

This would allow the community to use & test it so you could get more feedback while we wait for the rest of your dev team to review this.

**Comment by LeakedDave** [comment]
/** @type {import('next').NextConfig} */
const withTM = require('next-transpile-modules')(['@stampmyvisa/react-flagpack']);

module.exports = withTM({
    trailingSlash: false,
    output: "export",
    images: { unoptimized: true },
    webpack: (config, { isServer }) => {
        config.module.rules.push({
            test: /\.svg$/,
            include: /node_modules\/@stampmyvisa\/react-flagpack\/dist\/flags/,
            use: [
                {
                    loader: 'file-loader',
                    options: {
                        name: '[path][name].[hash].[ext]', // Update this line
                        outputPath: 'static/flags/',
                        publicPath: '/_next/static/flags/',
                        emitFile: !isServer,
                    },
                },
            ],
        });

        return config;
    },
})

This is how I'm fixing it with the existing package

**Comment by depsimon** [comment]
> This is how I'm fixing it with the existing package

I'm using Vite, but I'll try to see if I can make it work in a similar way. Thanks for your solution!

**Review by donovanroubos — APPROVED** [review]

**Comment by zoeyfrisart** [comment]
Hi all, this is now published on NPM, you can install it by bumping your version to `^2.0.2`, be sure to follow the migration guide https://github.com/Yummygum/react-flagpack/tree/v2.0.2?tab=readme-ov-file#migrating-to-200

**Pull request merged**
